# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "689a26aa08ca994c39fb72e02b4b4c27"
name = "shop-test-app"
handle = "shop-test-app-45"
application_url = "https://sun-fog-prescription-computer.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "frontend-stop-test-app.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sun-fog-prescription-computer.trycloudflare.com/auth/callback",
  "https://sun-fog-prescription-computer.trycloudflare.com/auth/shopify/callback",
  "https://sun-fog-prescription-computer.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
